apiVersion: v1
kind: Secret
metadata:
  name: repo-example-prod-runtime-secrets
  namespace: repo-example-prod
  labels:
    idea.rnen.kr/project: repo-example
    idea.rnen.kr/environment: prod
type: Opaque
stringData:
  DATABASE_URL: |-
    postgresql://idea:replace-me-prod-postgres@db:5432/idea_app_prod
  POSTGRES_PASSWORD: |-
    replace-me-prod-postgres
