apiVersion: v1
kind: Secret
metadata:
  name: repo-example-dev-runtime-secrets
  namespace: repo-example-dev
  labels:
    idea.rnen.kr/project: repo-example
    idea.rnen.kr/environment: dev
type: Opaque
stringData:
  DATABASE_URL: |-
    postgresql://idea:replace-me-dev-postgres@db:5432/idea_app_dev
  POSTGRES_PASSWORD: |-
    replace-me-dev-postgres
